"""add rosters table

Revision ID: 05c2f374f91b
Revises: 811b6c4346c0
Create Date: 2025-09-09 21:44:28.522920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c2f374f91b'
down_revision: Union[str, Sequence[str], None] = '811b6c4346c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rosters',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('jersey', sa.Integer(), nullable=True),
    sa.Column('player_cfbd_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('season', 'team_id', 'player_id')
    )
    op.create_index(op.f('ix_rosters_player_cfbd_id'), 'rosters', ['player_cfbd_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rosters_player_cfbd_id'), table_name='rosters')
    op.drop_table('rosters')
    # ### end Alembic commands ###
