"""init tables

Revision ID: 646a0b674947
Revises: 
Create Date: 2025-09-08 19:35:53.428440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646a0b674947'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('primary_pos', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('school')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('players')
    # ### end Alembic commands ###
